# Generated by Django 3.1.5 on 2021-02-16 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventname', models.CharField(max_length=100)),
                ('eventtime', models.TimeField(default=0)),
                ('eventdate', models.DateField(default=django.utils.timezone.now)),
                ('organizingcommunity', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='historydonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField(default='0')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bloodgroup', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField(default='0')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bloodgroup', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('age', models.IntegerField(default='0')),
                ('bloodgroup', models.CharField(max_length=4)),
            ],
        ),
    ]
