# Generated by Django 3.1.5 on 2021-02-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0002_auto_20210216_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventtime',
            field=models.TimeField(default='0'),
        ),
    ]
