# Generated by Django 3.1.5 on 2021-02-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0003_auto_20210216_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user.svg', upload_to=''),
        ),
    ]
