# Generated by Django 3.1.5 on 2021-02-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0004_auto_20210216_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user.svg', upload_to='pics'),
        ),
    ]
